exclude: ^nolibc/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.16.0
    hooks:
      - id: pretty-format-yaml
        args: [--autofix, --offset, '2']
      - id: pretty-format-toml
        args: [--autofix]
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.1
    hooks:
      - id: clang-format
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: remove-tabs
        exclude: '[mM]akefile[^\/]*$|.*\.mk$'
