name: "Release"

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'What version to release.'
        required: true

jobs:
  release:
    name: "New Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: "Install cross-compilers"
        run: sudo apt-get install -y gcc-aarch64-linux-gnu gcc-riscv64-linux-gnu qemu-user-static

      - name: "Build linuxX64"
        run: make NOLIBC=1 CC=gcc && mv qmk_id qmk_id-linuxX64 && make clean

      - name: "Build linuxARM64"
        run: make NOLIBC=1 CC=aarch64-linux-gnu-gcc && mv qmk_id qmk_id-linuxARM64 && make clean

      - name: "Build linuxRV64"
        run: make NOLIBC=1 CC=riscv64-linux-gnu-gcc && mv qmk_id qmk_id-linuxRV64 && make clean

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: v${{ github.event.inputs.release_tag }}
          files: |
            50-qmk.rules
            qmk_id-linuxX64
            qmk_id-linuxARM64
            qmk_id-linuxRV64
            README.md
